class_name Enums
extends RefCounted

enum Rarity { COMMON, UNCOMMON, RARE, EPIC, LEGENDARY, CURSED }
enum Tier { TIER_1, TIER_2, TIER_3, TIER_4 }
enum StackType { LINEAR, HYPERBOLIC, EXPONENTIAL, CAPPED }
enum TriggerType { ON_HIT, ON_CRIT, ON_KILL, ON_DASH, ON_TAKE_DAMAGE, ON_LEVEL_UP, PASSIVE_STAT }
enum TargetMode { NEAREST, LOWEST_HEALTH, RANDOM, HIGHEST_DENSITY }
